wandb_version: 1

wandb_flag:
  desc: null
  value: false
seed:
  desc: null
  value: 42
debug:
  desc: null
  value: false
exp_name:
  desc: null
  value: Baselinev2
comment:
  desc: null
  value: unet-efficientnet_b1-224x224-aug2-split2
model_name:
  desc: null
  value: UNet
backbone:
  desc: null
  value: efficientnet-b1
train_bs:
  desc: null
  value: 128
valid_bs:
  desc: null
  value: 256
img_size:
  desc: null
  value:
  - 224
  - 224
epochs:
  desc: null
  value: 3
lr:
  desc: null
  value: 0.002
scheduler:
  desc: null
  value: CosineAnnealingLR
min_lr:
  desc: null
  value: 1.0e-06
T_max:
  desc: null
  value: 753
T_0:
  desc: null
  value: 25
warmup_epochs:
  desc: null
  value: 0
wd:
  desc: null
  value: 1.0e-06
n_accumulate:
  desc: null
  value: 1
n_fold:
  desc: null
  value: 5
num_classes:
  desc: null
  value: 1
device:
  desc: null
  value: cpu
_wandb:
  desc: null
  value:
    python_version: 3.9.12
    cli_version: 0.16.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1705321654.183844
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      - 80
      2:
      - 1
      - 5
      - 53
      - 55
      - 80
      3:
      - 1
      - 3
      - 13
      - 16
      - 23
      4: 3.9.12
      5: 0.16.1
      8:
      - 2
      - 3
      - 5
      13: windows-amd64
